const LOGIN_USER='gerant';const LOGIN_PASS='Palace2026';
const loginScreen=document.getElementById('loginScreen'),app=document.getElementById('app');
if(sessionStorage.getItem('palaceGerant')==='1')showApp();
document.getElementById('loginForm').addEventListener('submit',e=>{e.preventDefault();const u=document.getElementById('user').value.trim(),p=document.getElementById('pass').value;if(u===LOGIN_USER&&p===LOGIN_PASS){sessionStorage.setItem('palaceGerant','1');showApp()}else document.getElementById('loginError').textContent='Identifiant ou mot de passe incorrect.'});
document.getElementById('logout').onclick=()=>{sessionStorage.removeItem('palaceGerant');location.reload()};
function showApp(){loginScreen.classList.add('hidden');app.classList.remove('hidden');renderAll()}
const defaults=[{name:"Carré d’agneau",cat:"Plats",price:2400},{name:"Filet de poisson",cat:"Plats",price:2200},{name:"Risotto du Palace",cat:"Plats",price:1900},{name:"Dessert signature",cat:"Desserts",price:900},{name:"Vin rouge — bouteille",cat:"Vin",price:4500},{name:"Vin blanc — bouteille",cat:"Vin",price:4500},{name:"Whisky — verre",cat:"Whisky",price:1200},{name:"Whisky — bouteille",cat:"Whisky",price:12000},{name:"Bière — bouteille",cat:"Bière",price:700},{name:"Bière — verre",cat:"Bière",price:600}];
let items=JSON.parse(localStorage.getItem('palaceMenu')||'null')||defaults;localStorage.setItem('palaceMenu',JSON.stringify(items));
function save(){localStorage.setItem('palaceMenu',JSON.stringify(items));renderMenu()}
function renderMenu(){document.getElementById('menu').innerHTML=items.map((x,i)=>`<div class="item"><input value="${x.name}" onchange="items[${i}].name=this.value;save()"><input value="${x.cat}" onchange="items[${i}].cat=this.value;save()"><input class="price" type="number" value="${x.price}" onchange="items[${i}].price=+this.value;save()"><button onclick="items.splice(${i},1);save()">Supprimer</button></div>`).join('')}
function add(){const name=document.getElementById('name').value.trim(),cat=document.getElementById('cat').value.trim()||'Plats',price=+document.getElementById('price').value;if(!name||!price)return alert('Indiquez le nom et le prix.');items.push({name,cat,price});save();document.getElementById('name').value='';document.getElementById('cat').value='';document.getElementById('price').value=''}
function renderOrders(){const orders=JSON.parse(localStorage.getItem('palaceOrders')||'[]');document.getElementById('ordersCount').textContent=orders.length;const box=document.getElementById('orders');if(!orders.length){box.innerHTML='<p class="hint">Aucune commande reçue.</p>';return}box.innerHTML=orders.map((o,i)=>`<div class="order"><div><b>${o.id}</b> · Table ${o.table}</div><small>${o.createdAt} · ${o.client}</small><ul>${o.items.map(x=>`<li>${x.qty} × ${x.name} <span>${Number(x.price*x.qty).toLocaleString('fr-FR')} DA</span></li>`).join('')}</ul><strong class="total">${Number(o.total).toLocaleString('fr-FR')} DA</strong><select onchange="setStatus(${i},this.value)"><option ${o.status==='Nouvelle'?'selected':''}>Nouvelle</option><option ${o.status==='En préparation'?'selected':''}>En préparation</option><option ${o.status==='Servie'?'selected':''}>Servie</option><option ${o.status==='Annulée'?'selected':''}>Annulée</option></select></div>`).join('')}
function setStatus(i,status){const orders=JSON.parse(localStorage.getItem('palaceOrders')||'[]');if(orders[i])orders[i].status=status;localStorage.setItem('palaceOrders',JSON.stringify(orders));renderOrders()}
function renderTables(){const t=document.getElementById('tables');t.innerHTML='';for(let i=1;i<=20;i++){const n=String(i).padStart(2,'0');t.innerHTML+=`<div class="table"><b>Table ${n}</b><img src="../assets/qr/table-${n}.png" alt="QR Table ${n}"><small>Scanner pour commander</small><a class="qr-link" target="_blank" href="../table.html?table=${n}">Ouvrir</a></div>`}}
function renderAll(){renderMenu();renderOrders();renderTables();setInterval(renderOrders,3000)}
