const params=new URLSearchParams(location.search);const table=(params.get('table')||'01').padStart(2,'0');
document.getElementById('tableTitle').textContent='Table '+table;
const defaults=[
{name:"Carré d’agneau",cat:"Plats",price:2400,desc:"Agneau rôti, accompagnement maison."},{name:"Filet de poisson",cat:"Plats",price:2200,desc:"Poisson du jour, sauce du chef."},{name:"Risotto du Palace",cat:"Plats",price:1900,desc:"Crémeux et parfumé, recette maison."},{name:"Dessert signature",cat:"Desserts",price:900,desc:"Création sucrée du chef."},
{name:"Vin rouge — bouteille",cat:"Vin",price:4500,desc:"Sélection du Palace."},{name:"Vin blanc — bouteille",cat:"Vin",price:4500,desc:"Sélection du Palace."},{name:"Whisky — verre",cat:"Whisky",price:1200,desc:"Service au verre."},{name:"Whisky — bouteille",cat:"Whisky",price:12000,desc:"Sélection du Palace."},{name:"Bière — bouteille",cat:"Bière",price:700,desc:"Bière fraîche."},{name:"Bière — verre",cat:"Bière",price:600,desc:"Service frais."}];
let menu=JSON.parse(localStorage.getItem('palaceMenu')||'null')||defaults;let cart=JSON.parse(localStorage.getItem('palaceCart_'+table)||'{}');
const money=n=>Number(n).toLocaleString('fr-FR')+' DA';
function renderMenu(){document.getElementById('menuGrid').innerHTML=menu.map((x,i)=>`<article class="menu-card"><div class="price">${x.cat}</div><h3>${x.name}</h3><p>${x.desc||''}</p><strong class="price">${money(x.price)}</strong><button class="btn gold add" data-i="${i}">Ajouter</button></article>`).join('');document.querySelectorAll('.add').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;cart[i]=(cart[i]||0)+1;save()})}
function save(){localStorage.setItem('palaceCart_'+table,JSON.stringify(cart));renderCart()}
function renderCart(){let total=0,html='';Object.entries(cart).forEach(([i,q])=>{const x=menu[i];if(!x||!q)return;total+=x.price*q;html+=`<div class="cart-line"><span>${q} × ${x.name}</span><strong>${money(x.price*q)}</strong><button onclick="change(${i},-1)">−</button><button onclick="change(${i},1)">+</button></div>`});document.getElementById('cart').innerHTML=html||'<p class="small-note">Aucun article.</p>';document.getElementById('total').textContent=money(total)}
function change(i,n){cart[i]=(cart[i]||0)+n;if(cart[i]<=0)delete cart[i];save()}
document.getElementById('send').onclick=()=>{let lines=[];let total=0;Object.entries(cart).forEach(([i,q])=>{const x=menu[i];if(x&&q){lines.push({name:x.name,cat:x.cat,price:x.price,qty:q});total+=x.price*q}});if(!lines.length)return alert('Ajoutez au moins un article.');const order={id:'CMD-'+Date.now().toString().slice(-6),table,client:document.getElementById('clientName').value.trim()||'Client table '+table,items:lines,total,status:'Nouvelle',createdAt:new Date().toLocaleString('fr-FR')};const orders=JSON.parse(localStorage.getItem('palaceOrders')||'[]');orders.unshift(order);localStorage.setItem('palaceOrders',JSON.stringify(orders));cart={};save();alert('Commande envoyée à la caisse. Merci !');};
renderMenu();renderCart();
